from __future__ import annotations
from abc import ABC, abstractmethod
from langgraph.graph import START, StateGraph, MessagesState, END
from langchain.chat_models import init_chat_model
from langchain_core.tools import tool
from src.core import vector_store
from langchain_core.messages import SystemMessage

@tool(response_format="content_and_artifact")
def retrieve(query: str):
    """Retrieve information related to a query."""
    retrieved_docs = vector_store.similarity_search(query, k=1)
    serialized = "\n\n".join(
        (f"Source: {doc.metadata}\n" f"Content: {doc.page_content}")
        for doc in retrieved_docs
    )
    return serialized, retrieved_docs

class LlmFactory(ABC):
    @abstractmethod
    def factory_method(self):
        pass

    def operation(self):
        llm = self.factory_method
        return f"Creator: The same creator's code has just worked with {llm.generate()}"

class Llm(ABC):
    @abstractmethod
    def query_or_respond(self, state: MessagesState):
        pass

    @abstractmethod
    def generate(self, state: MessagesState):
        pass


class GptCreator(LlmFactory):
    def factory_method(self):
        return GptCreator()
    
class MistralCreator(LlmFactory):
    def factory_method(self):
        return MistralCreator()
    
class GptModel(Llm):
    def __init__(self):
        self.llm = init_chat_model("gpt-4o-mini", model_provider="openai")
    def query_or_respond(self, state: MessagesState):
        """Generate tool call for retrieval or respond."""
        llm_with_tools = self.llm.bind_tools([retrieve])
        response = llm_with_tools.invoke(state["messages"])
        # MessagesState appends messages to state instead of overwriting
        return {"messages": [response]}

    def generate(self, state: MessagesState):
        recent_tool_messages = []
        for message in reversed(state["messages"]):
            if message.type == "tool":
                recent_tool_messages.append(message)
            else:
                break
        tool_messages = recent_tool_messages[::-1]

        # Format into prompt
        docs_content = "\n\n".join(doc.content for doc in tool_messages)
        system_message_content = (
            "You are an assistant for question-answering tasks. "
            "Use the following pieces of retrieved context to answer "
            "the question. If you don't know the answer, say that you "
            "don't know. Use three sentences maximum and keep the "
            "answer concise."
            "\n\n"
            f"{docs_content}"
        )
        conversation_messages = [
            message
            for message in state["messages"]
            if message.type in ("human", "system")
            or (message.type == "ai" and not message.tool_calls)
        ]
        prompt = [SystemMessage(system_message_content)] + conversation_messages

        # Run
        response = self.llm.invoke(prompt)
        return {"messages": [response]}
    
class MistralModel(Llm):
    def query_or_respond(self, state: MessagesState):
        return "query for mistral"
    
    def generate(self):
        return "response generated by mistral"
    

def llm_client(factory: LlmFactory):
        print(f"Client: I'm not aware of the creator's class, but it still works.\n"
          f"{factory.generate()}", end="")
        

if __name__ == "__main__":
    # Example usage of the factory design pattern
    print("Test 1 : ")
    llm_client(GptModel())
    print("\nTest 2")
    llm_client(MistralModel())